-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2018.1 Schlumberger
-- User name   : eremyanga
-- Date        : Monday, November 30 2020 13:23:17
-- Project     : prepare_v4.pet
-- Generated ]

EQUIL                                  -- Generated : Petrel
          2450       241.36         2450            0 1*            0 0 0 0 /

RPTSOL                                 -- Generated : Petrel
  FIP /

