-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2018.1 Schlumberger
-- User name   : eremyanga
-- Date        : Monday, November 30 2020 13:23:17
-- Project     : prepare_v4.pet
-- Generated ]

RPTSCHED                               -- Generated : Petrel
  FIP WELLS /

SKIP                                   -- Generated : Petrel
--Default history strategy generated.

ENDSKIP                                -- Generated : Petrel

--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Default history strategy generated.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Default history strategy generated.


--Default history strategy generated.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Default history strategy generated.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Default history strategy generated.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Default history strategy generated.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Default history strategy generated.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


--Hint: Drag producers into PROD FOLDER, injectors into INJ FOLDER, set target Field production rate in Group rate production control rule, check the production BHP limit in Well pressure production control rule and set injection BHP limit in Well water injection control rule.


WELSPECS                               -- Generated : Petrel
--'P1' is the simulation well name used to describe flow from 'P1'
--
  P1 'GROUP 1' 17 7 1* OIL /
  /

COMPDAT                                -- Generated : Petrel
  P1 17 7 1 1 OPEN 1* 0.327846 0.1905 32.6578 0 1* Z 19.8005 /
  P1 17 7 2 2 OPEN 1* 2.44662 0.1905 243.716 0 1* Z 19.8005 /
  P1 17 7 3 3 OPEN 1* 1.98463 0.1905 197.696 0 1* Z 19.8005 /
  P1 17 7 4 4 OPEN 1* 1.80503 0.1905 179.804 0 1* Z 19.8005 /
  P1 17 7 5 5 OPEN 1* 2.52937 0.1905 251.958 0 1* Z 19.8005 /
  P1 17 7 6 6 OPEN 1* 1.15129 0.1905 114.684 0 1* Z 19.8005 /
  P1 17 7 7 7 OPEN 1* 0.837424 0.1905 83.4185 0 1* Z 19.8005 /
  P1 17 7 8 8 OPEN 1* 1.63106 0.1905 162.475 0 1* Z 19.8005 /
  P1 17 7 9 9 OPEN 1* 0.2567 0.1905 25.5707 0 1* Z 19.8005 /
  /

GRUPTREE                               -- Generated : Petrel
  'GROUP 1' FIELD /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 197.595 215.236 4* 240.398 /
  /

WELTARG                                -- Generated : Petrel
  P1 BHP 50 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2010 /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 154.045 196.415 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2010 /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 121.987 168.78 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2010 /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 98.7208 142.512 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2010 /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 80.233 118.389 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2010 /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 65.9492 98.2148 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2010 /
  /

WELSPECS                               -- Generated : Petrel
--'I2' is the simulation well name used to describe flow from 'I2'
--
  I2 'GROUP 1' 19 12 1* WATER /
  /

COMPDAT                                -- Generated : Petrel
  I2 19 12 1 1 OPEN 1* 0.143195 0.1905 14.264 0 1* Z 19.7998 /
  I2 19 12 2 2 OPEN 1* 0.645333 0.1905 64.2832 0 1* Z 19.7999 /
  I2 19 12 3 3 OPEN 1* 2.5323 0.1905 252.249 0 1* Z 19.7999 /
  I2 19 12 4 4 OPEN 1* 1.83814 0.1905 183.102 0 1* Z 19.7999 /
  I2 19 12 5 5 OPEN 1* 0.876833 0.1905 87.3436 0 1* Z 19.7999 /
  I2 19 12 6 6 OPEN 1* 1.13488 0.1905 113.048 0 1* Z 19.7999 /
  I2 19 12 7 7 OPEN 1* 0.449196 0.1905 44.7456 0 1* Z 19.7999 /
  I2 19 12 8 8 OPEN 1* 1.0183 0.1905 101.436 0 1* Z 19.7999 /
  I2 19 12 9 9 OPEN 1* 0.708022 0.1905 70.5279 0 1* Z 19.7999 /
  I2 19 12 10 10 OPEN 1* 0.336367 0.1905 33.5064 0 1* Z 19.7999 /
  I2 19 12 11 11 OPEN 1* 0.257679 0.1905 25.6681 0 1* Z 19.7999 /
  I2 19 12 12 12 OPEN 1* 0.238806 0.1905 23.7881 0 1* Z 19.7999 /
  I2 19 12 13 13 OPEN 1* 0.0452665 0.1905 4.50912 0 1* Z 19.7999 /
  I2 19 12 14 14 OPEN 1* 0.157946 0.1905 15.7334 0 1* Z 19.7999 /
  I2 19 12 15 15 OPEN 1* 0.1273 0.1905 12.6807 0 1* Z 19.7999 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 176.24 0 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 66.2979 104.973 4* 120 /
  /

WELTARG                                -- Generated : Petrel
  I2 BHP 500 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2010 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 178.763 167.953 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 64.9428 108.902 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2010 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 179.768 168.566 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 63.3793 111.589 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2010 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 180.486 168.728 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 61.8619 113.939 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2010 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 181.155 168.8 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 60.5372 116.033 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2010 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 181.801 168.85 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 59.2664 118.047 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2011 /
  /

WELSPECS                               -- Generated : Petrel
--'P2' is the simulation well name used to describe flow from 'P2'
--
  P2 'GROUP 1' 13 12 1* OIL /
  /

COMPDAT                                -- Generated : Petrel
  P2 13 12 1 1 OPEN 1* 0.124078 0.1905 12.3598 0 1* Z 19.8007 /
  P2 13 12 2 2 OPEN 1* 0.603338 0.1905 60.1005 0 1* Z 19.8007 /
  P2 13 12 3 3 OPEN 1* 2.53074 0.1905 252.095 0 1* Z 19.8007 /
  P2 13 12 4 4 OPEN 1* 1.57532 0.1905 156.923 0 1* Z 19.8007 /
  P2 13 12 5 5 OPEN 1* 1.35654 0.1905 135.13 0 1* Z 19.8007 /
  P2 13 12 6 6 OPEN 1* 1.19667 0.1905 119.205 0 1* Z 19.8007 /
  P2 13 12 7 7 OPEN 1* 1.50749 0.1905 150.166 0 1* Z 19.8006 /
  P2 13 12 8 8 OPEN 1* 1.70007 0.1905 169.349 0 1* Z 19.8006 /
  P2 13 12 9 9 OPEN 1* 1.49704 0.1905 149.125 0 1* Z 19.8006 /
  P2 13 12 10 10 OPEN 1* 0.95976 0.1905 95.6048 0 1* Z 19.8006 /
  P2 13 12 11 11 OPEN 1* 1.84545 0.1905 183.831 0 1* Z 19.8006 /
  P2 13 12 12 12 OPEN 1* 1.00991 0.1905 100.601 0 1* Z 19.8006 /
  P2 13 12 13 13 OPEN 1* 0.26494 0.1905 26.3915 0 1* Z 19.8006 /
  P2 13 12 14 14 OPEN 1* 0.206919 0.1905 20.6119 0 1* Z 19.8006 /
  P2 13 12 15 15 OPEN 1* 0.160872 0.1905 16.025 0 1* Z 19.8006 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 449.603 168.896 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 57.6251 133.749 4* 120 /
  P2 OPEN LRAT 220.886 4.06078 4* 0 /
  /

WELTARG                                -- Generated : Petrel
  P2 BHP 50 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2011 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 427.332 188.529 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 54.7392 140.268 4* 120 /
  P2 OPEN LRAT 197.761 13.5659 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2011 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 414.765 187.389 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 52.115 145.076 4* 120 /
  P2 OPEN LRAT 174.364 24.1421 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2011 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 407.072 186.627 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 49.9288 148.729 4* 120 /
  P2 OPEN LRAT 157.489 34.4357 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2011 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 403.446 186.094 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 48.0487 152.19 4* 120 /
  P2 OPEN LRAT 144.703 43.783 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2011 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 402.345 185.81 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 46.3985 155.433 4* 120 /
  P2 OPEN LRAT 134.999 51.7377 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2011 /
  /

WELSPECS                               -- Generated : Petrel
--'I3' is the simulation well name used to describe flow from 'I3'
--
  I3 'GROUP 1' 7 14 1* WATER /
  /

COMPDAT                                -- Generated : Petrel
  I3 7 14 1 1 OPEN 1* 0.089362 0.1905 8.90164 0 1* Z 19.8006 /
  I3 7 14 2 2 OPEN 1* 0.239633 0.1905 23.8706 0 1* Z 19.8006 /
  I3 7 14 3 3 OPEN 1* 1.44622 0.1905 144.063 0 1* Z 19.8006 /
  I3 7 14 4 4 OPEN 1* 1.51091 0.1905 150.506 0 1* Z 19.8006 /
  I3 7 14 5 5 OPEN 1* 2.7686 0.1905 275.789 0 1* Z 19.8006 /
  I3 7 14 6 6 OPEN 1* 1.58424 0.1905 157.812 0 1* Z 19.8006 /
  I3 7 14 7 7 OPEN 1* 0.397179 0.1905 39.5643 0 1* Z 19.8006 /
  I3 7 14 8 8 OPEN 1* 0.574011 0.1905 57.1791 0 1* Z 19.8006 /
  I3 7 14 9 9 OPEN 1* 1.18235 0.1905 117.778 0 1* Z 19.8007 /
  I3 7 14 10 10 OPEN 1* 0.683267 0.1905 68.0625 0 1* Z 19.8007 /
  I3 7 14 11 11 OPEN 1* 0.515356 0.1905 51.3363 0 1* Z 19.8007 /
  I3 7 14 12 12 OPEN 1* 0.347269 0.1905 34.5926 0 1* Z 19.8007 /
  I3 7 14 13 13 OPEN 1* 0.299613 0.1905 29.8455 0 1* Z 19.8007 /
  I3 7 14 14 14 OPEN 1* 0.301246 0.1905 30.0081 0 1* Z 19.8007 /
  I3 7 14 15 15 OPEN 1* 0.190598 0.1905 18.9861 0 1* Z 19.8007 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 234.226 185.702 6* RATE /
  I3 WATER OPEN 146.172 0 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 42.8052 144.319 4* 120 /
  P2 OPEN LRAT 124.488 55.5854 4* 120 /
  /

WELTARG                                -- Generated : Petrel
  I3 BHP 500 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2011 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 228.525 171.746 6* RATE /
  I3 WATER OPEN 145.693 174.052 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 41.6254 142.107 4* 120 /
  P2 OPEN LRAT 118.091 60.1531 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2011 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 225.29 170.614 6* RATE /
  I3 WATER OPEN 147.262 174.611 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 40.9396 142.161 4* 120 /
  P2 OPEN LRAT 113.158 64.596 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2011 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 223.059 170.187 6* RATE /
  I3 WATER OPEN 149.003 174.763 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 40.3141 142.807 4* 120 /
  P2 OPEN LRAT 108.683 68.9785 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2011 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 221.379 169.938 6* RATE /
  I3 WATER OPEN 150.785 174.823 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 39.7341 143.578 4* 120 /
  P2 OPEN LRAT 104.953 72.9394 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2011 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 220.009 169.756 6* RATE /
  I3 WATER OPEN 152.433 174.881 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 39.162 144.414 4* 120 /
  P2 OPEN LRAT 101.462 76.7543 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2012 /
  /

WELSPECS                               -- Generated : Petrel
--'P3' is the simulation well name used to describe flow from 'P3'
--
  P3 'GROUP 1' 8 9 1* OIL /
  /

COMPDAT                                -- Generated : Petrel
  P3 8 9 1 1 OPEN 1* 0.10461 0.1905 10.4206 0 1* Z 19.8011 /
  P3 8 9 2 2 OPEN 1* 0.594127 0.1905 59.1832 0 1* Z 19.8011 /
  P3 8 9 3 3 OPEN 1* 2.5646 0.1905 255.469 0 1* Z 19.8011 /
  P3 8 9 4 4 OPEN 1* 1.75237 0.1905 174.56 0 1* Z 19.8011 /
  P3 8 9 5 5 OPEN 1* 0.846223 0.1905 84.2954 0 1* Z 19.8011 /
  P3 8 9 6 6 OPEN 1* 0.743571 0.1905 74.0699 0 1* Z 19.8011 /
  P3 8 9 7 7 OPEN 1* 0.809337 0.1905 80.6211 0 1* Z 19.8011 /
  P3 8 9 8 8 OPEN 1* 0.768538 0.1905 76.5569 0 1* Z 19.8011 /
  P3 8 9 9 9 OPEN 1* 0.506532 0.1905 50.4575 0 1* Z 19.8011 /
  P3 8 9 10 10 OPEN 1* 0.318243 0.1905 31.7013 0 1* Z 19.8011 /
  P3 8 9 11 11 OPEN 1* 0.440179 0.1905 43.8479 0 1* Z 19.8011 /
  P3 8 9 12 12 OPEN 1* 1.65027 0.1905 164.389 0 1* Z 19.8011 /
  P3 8 9 13 13 OPEN 1* 0.552694 0.1905 55.0559 0 1* Z 19.8011 /
  P3 8 9 14 14 OPEN 1* 0.430978 0.1905 42.9313 0 1* Z 19.8011 /
  P3 8 9 15 15 OPEN 1* 0.292698 0.1905 29.1568 0 1* Z 19.8011 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 351.2 169.601 6* RATE /
  I3 WATER OPEN 246.943 174.94 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 39.6316 157.564 4* 120 /
  P2 OPEN LRAT 98.4742 87.4865 4* 120 /
  P3 OPEN LRAT 183.311 0.926757 4* 0 /
  /

WELTARG                                -- Generated : Petrel
  P3 BHP 50 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2012 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 342.743 180.824 6* RATE /
  I3 WATER OPEN 245.689 182.105 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 38.5566 161.889 4* 120 /
  P2 OPEN LRAT 93.9227 93.9768 4* 120 /
  P3 OPEN LRAT 172.878 3.82566 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2012 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 338.662 180.632 6* RATE /
  I3 WATER OPEN 246.414 181.526 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 37.3876 164.276 4* 120 /
  P2 OPEN LRAT 89.5104 99.5958 4* 120 /
  P3 OPEN LRAT 164.488 7.33191 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2012 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 334.225 180.31 6* RATE /
  I3 WATER OPEN 246.452 181.467 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 36.4079 165.883 4* 120 /
  P2 OPEN LRAT 85.7166 104.454 4* 120 /
  P3 OPEN LRAT 155.487 10.901 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2012 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 327.376 179.897 6* RATE /
  I3 WATER OPEN 246.256 181.466 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 35.4745 167.007 4* 120 /
  P2 OPEN LRAT 82.069 109.013 4* 120 /
  P3 OPEN LRAT 144.978 15.2106 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2012 /
  /

WCONINJH                               -- Generated : Petrel
  I2 WATER OPEN 321.732 179.248 6* RATE /
  I3 WATER OPEN 243.901 181.448 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 34.6759 167.933 4* 120 /
  P2 OPEN LRAT 79.0473 112.934 4* 120 /
  P3 OPEN LRAT 132.413 19.658 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2012 /
  /

WELSPECS                               -- Generated : Petrel
--'I1' is the simulation well name used to describe flow from 'I1'
--
  I1 'GROUP 1' 12 4 1* WATER /
  /

COMPDAT                                -- Generated : Petrel
  I1 12 4 1 1 OPEN 1* 0.0647751 0.1905 6.45258 0 1* Z 19.8025 /
  I1 12 4 2 2 OPEN 1* 0.261943 0.1905 26.0935 0 1* Z 19.8025 /
  I1 12 4 3 3 OPEN 1* 1.69991 0.1905 169.336 0 1* Z 19.8025 /
  I1 12 4 4 4 OPEN 1* 1.80988 0.1905 180.291 0 1* Z 19.8024 /
  I1 12 4 5 5 OPEN 1* 1.18338 0.1905 117.882 0 1* Z 19.8024 /
  I1 12 4 6 6 OPEN 1* 0.894603 0.1905 89.1159 0 1* Z 19.8024 /
  I1 12 4 7 7 OPEN 1* 0.641882 0.1905 63.941 0 1* Z 19.8023 /
  I1 12 4 8 8 OPEN 1* 0.362341 0.1905 36.0946 0 1* Z 19.8023 /
  I1 12 4 9 9 OPEN 1* 0.624281 0.1905 62.1876 0 1* Z 19.8023 /
  I1 12 4 10 10 OPEN 1* 0.505699 0.1905 50.3752 0 1* Z 19.8023 /
  I1 12 4 11 11 OPEN 1* 0.251398 0.1905 25.043 0 1* Z 19.8022 /
  I1 12 4 12 12 OPEN 1* 0.242435 0.1905 24.1501 0 1* Z 19.8022 /
  I1 12 4 13 13 OPEN 1* 0.0876729 0.1905 8.73352 0 1* Z 19.8022 /
  I1 12 4 15 15 OPEN 1* 0.0452258 0.1905 4.50515 0 1* Z 19.8021 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 99.987 0 6* RATE /
  I2 WATER OPEN 262.692 178.695 6* RATE /
  I3 WATER OPEN 200.003 181.256 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 35.2871 171.151 4* 120 /
  P2 OPEN LRAT 77.3121 113.603 4* 120 /
  P3 OPEN LRAT 122.77 24.8375 4* 120 /
  /

WELTARG                                -- Generated : Petrel
  I1 BHP 500 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2012 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 101.923 172.598 6* RATE /
  I2 WATER OPEN 259.768 174.409 6* RATE /
  I3 WATER OPEN 199.155 176.488 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 35.1449 172.024 4* 120 /
  P2 OPEN LRAT 75.874 115.502 4* 120 /
  P3 OPEN LRAT 115.436 29.6018 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2012 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 104.108 172.878 6* RATE /
  I2 WATER OPEN 257.106 174.116 6* RATE /
  I3 WATER OPEN 198.386 176.215 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 34.8351 172.725 4* 120 /
  P2 OPEN LRAT 74.4254 117.611 4* 120 /
  P3 OPEN LRAT 109.522 33.8953 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2012 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 106.102 172.987 6* RATE /
  I2 WATER OPEN 255.009 173.869 6* RATE /
  I3 WATER OPEN 197.947 176.066 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 34.4553 173.549 4* 120 /
  P2 OPEN LRAT 72.9409 119.836 4* 120 /
  P3 OPEN LRAT 104.101 38.1414 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2012 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 107.983 173.066 6* RATE /
  I2 WATER OPEN 253.411 173.665 6* RATE /
  I3 WATER OPEN 197.834 175.965 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 34.0682 174.427 4* 120 /
  P2 OPEN LRAT 71.539 121.963 4* 120 /
  P3 OPEN LRAT 99.62 42.0719 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2012 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 109.67 173.157 6* RATE /
  I2 WATER OPEN 252.219 173.502 6* RATE /
  I3 WATER OPEN 197.91 175.895 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 33.6692 175.386 4* 120 /
  P2 OPEN LRAT 70.1505 124.134 4* 120 /
  P3 OPEN LRAT 95.5683 45.8122 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2013 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 111.278 173.227 6* RATE /
  I2 WATER OPEN 251.303 173.372 6* RATE /
  I3 WATER OPEN 198.155 175.84 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 33.2738 176.36 4* 120 /
  P2 OPEN LRAT 68.8493 126.266 4* 120 /
  P3 OPEN LRAT 91.9853 49.3021 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2013 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 112.695 173.311 6* RATE /
  I2 WATER OPEN 250.652 173.263 6* RATE /
  I3 WATER OPEN 198.537 175.798 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 32.9308 177.261 4* 120 /
  P2 OPEN LRAT 67.7431 128.179 4* 120 /
  P3 OPEN LRAT 89.1595 52.2766 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2013 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 114.009 173.385 6* RATE /
  I2 WATER OPEN 250.276 173.184 6* RATE /
  I3 WATER OPEN 198.989 175.783 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 32.5625 178.261 4* 120 /
  P2 OPEN LRAT 66.5616 130.245 4* 120 /
  P3 OPEN LRAT 86.3165 55.3486 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2013 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 115.345 173.432 6* RATE /
  I2 WATER OPEN 249.893 173.12 6* RATE /
  I3 WATER OPEN 199.475 175.762 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 32.2183 179.225 4* 120 /
  P2 OPEN LRAT 65.4566 132.186 4* 120 /
  P3 OPEN LRAT 83.7901 58.1412 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2013 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 116.537 173.507 6* RATE /
  I2 WATER OPEN 249.657 173.061 6* RATE /
  I3 WATER OPEN 200 175.751 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 31.8732 180.21 4* 120 /
  P2 OPEN LRAT 64.3674 134.118 4* 120 /
  P3 OPEN LRAT 81.3862 60.8506 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2013 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 117.66 173.565 6* RATE /
  I2 WATER OPEN 249.458 173.012 6* RATE /
  I3 WATER OPEN 200.55 175.738 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 31.5448 181.146 4* 120 /
  P2 OPEN LRAT 63.3646 135.919 4* 120 /
  P3 OPEN LRAT 79.2303 63.324 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2013 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 118.706 173.625 6* RATE /
  I2 WATER OPEN 249.385 172.969 6* RATE /
  I3 WATER OPEN 201.138 175.735 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 31.2115 182.105 4* 120 /
  P2 OPEN LRAT 62.3919 137.709 4* 120 /
  P3 OPEN LRAT 77.1678 65.7806 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2013 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 119.734 173.672 6* RATE /
  I2 WATER OPEN 249.32 172.935 6* RATE /
  I3 WATER OPEN 201.741 175.729 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 30.8792 183.056 4* 120 /
  P2 OPEN LRAT 61.4589 139.446 4* 120 /
  P3 OPEN LRAT 75.1933 68.1317 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2013 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 120.705 173.725 6* RATE /
  I2 WATER OPEN 249.295 172.904 6* RATE /
  I3 WATER OPEN 202.341 175.73 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 30.5637 183.978 4* 120 /
  P2 OPEN LRAT 60.5952 141.069 4* 120 /
  P3 OPEN LRAT 73.3914 70.3343 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2013 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 121.607 173.778 6* RATE /
  I2 WATER OPEN 249.33 172.878 6* RATE /
  I3 WATER OPEN 202.948 175.732 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 30.2429 184.921 4* 120 /
  P2 OPEN LRAT 59.7448 142.686 4* 120 /
  P3 OPEN LRAT 71.5879 72.5239 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2013 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 122.469 173.822 6* RATE /
  I2 WATER OPEN 249.373 172.856 6* RATE /
  I3 WATER OPEN 203.554 175.733 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 29.9343 185.836 4* 120 /
  P2 OPEN LRAT 58.9568 144.199 4* 120 /
  P3 OPEN LRAT 69.9128 74.5993 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2013 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 123.308 173.867 6* RATE /
  I2 WATER OPEN 249.516 172.837 6* RATE /
  I3 WATER OPEN 204.208 175.737 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 29.6153 186.782 4* 120 /
  P2 OPEN LRAT 58.176 145.723 4* 120 /
  P3 OPEN LRAT 68.2477 76.732 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2014 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 124.143 173.909 6* RATE /
  I2 WATER OPEN 249.701 172.824 6* RATE /
  I3 WATER OPEN 204.888 175.744 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 29.2982 187.736 4* 120 /
  P2 OPEN LRAT 57.4275 147.21 4* 120 /
  P3 OPEN LRAT 66.6202 78.907 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2014 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 124.927 173.953 6* RATE /
  I2 WATER OPEN 249.855 172.815 6* RATE /
  I3 WATER OPEN 205.532 175.751 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 29.0127 188.596 4* 120 /
  P2 OPEN LRAT 56.7805 148.532 4* 120 /
  P3 OPEN LRAT 65.1573 80.8687 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2014 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 125.691 173.999 6* RATE /
  I2 WATER OPEN 250.158 172.806 6* RATE /
  I3 WATER OPEN 206.233 175.763 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 28.703 189.557 4* 120 /
  P2 OPEN LRAT 56.0822 149.969 4* 120 /
  P3 OPEN LRAT 63.6085 82.9918 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2014 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 126.484 174.038 6* RATE /
  I2 WATER OPEN 250.444 172.808 6* RATE /
  I3 WATER OPEN 206.935 175.779 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 28.4065 190.501 4* 120 /
  P2 OPEN LRAT 55.4271 151.324 4* 120 /
  P3 OPEN LRAT 62.1998 85.0223 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2014 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 127.277 174.083 6* RATE /
  I2 WATER OPEN 250.811 172.808 6* RATE /
  I3 WATER OPEN 207.684 175.791 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 28.0965 191.49 4* 120 /
  P2 OPEN LRAT 54.7713 152.69 4* 120 /
  P3 OPEN LRAT 60.8551 87.0558 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2014 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 128.054 174.13 6* RATE /
  I2 WATER OPEN 251.187 172.817 6* RATE /
  I3 WATER OPEN 208.425 175.812 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 27.7981 192.461 4* 120 /
  P2 OPEN LRAT 54.1546 153.981 4* 120 /
  P3 OPEN LRAT 59.6343 88.9979 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2014 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 128.821 174.177 6* RATE /
  I2 WATER OPEN 251.617 172.825 6* RATE /
  I3 WATER OPEN 209.194 175.828 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 27.4865 193.478 4* 120 /
  P2 OPEN LRAT 53.532 155.285 4* 120 /
  P3 OPEN LRAT 58.4054 90.9783 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2014 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 129.583 174.224 6* RATE /
  I2 WATER OPEN 252.066 172.838 6* RATE /
  I3 WATER OPEN 209.977 175.848 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 27.1762 194.504 4* 120 /
  P2 OPEN LRAT 52.9294 156.564 4* 120 /
  P3 OPEN LRAT 57.2211 92.9205 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2014 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 130.323 174.271 6* RATE /
  I2 WATER OPEN 252.516 172.852 6* RATE /
  I3 WATER OPEN 210.747 175.87 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 26.8768 195.504 4* 120 /
  P2 OPEN LRAT 52.3714 157.786 4* 120 /
  P3 OPEN LRAT 56.1028 94.7796 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2014 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 131.051 174.319 6* RATE /
  I2 WATER OPEN 253.007 172.867 6* RATE /
  I3 WATER OPEN 211.536 175.892 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 26.567 196.537 4* 120 /
  P2 OPEN LRAT 51.8058 159.032 4* 120 /
  P3 OPEN LRAT 54.979 96.667 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2014 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 131.762 174.363 6* RATE /
  I2 WATER OPEN 253.47 172.885 6* RATE /
  I3 WATER OPEN 212.306 175.916 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 26.2673 197.536 4* 120 /
  P2 OPEN LRAT 51.2693 160.216 4* 120 /
  P3 OPEN LRAT 53.9139 98.4681 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2014 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 132.459 174.409 6* RATE /
  I2 WATER OPEN 253.969 172.902 6* RATE /
  I3 WATER OPEN 213.087 175.94 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 25.956 198.573 4* 120 /
  P2 OPEN LRAT 50.7262 161.413 4* 120 /
  P3 OPEN LRAT 52.8459 100.284 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2015 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 133.159 174.452 6* RATE /
  I2 WATER OPEN 254.483 172.921 6* RATE /
  I3 WATER OPEN 213.885 175.964 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 25.6525 199.61 4* 120 /
  P2 OPEN LRAT 50.1994 162.592 4* 120 /
  P3 OPEN LRAT 51.8431 102.053 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2015 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 133.816 174.497 6* RATE /
  I2 WATER OPEN 254.945 172.941 6* RATE /
  I3 WATER OPEN 214.631 175.99 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 25.3817 200.553 4* 120 /
  P2 OPEN LRAT 49.7378 163.645 4* 120 /
  P3 OPEN LRAT 50.9809 103.624 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2015 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 134.481 174.541 6* RATE /
  I2 WATER OPEN 255.505 172.96 6* RATE /
  I3 WATER OPEN 215.422 176.017 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 25.0885 201.602 4* 120 /
  P2 OPEN LRAT 49.2316 164.788 4* 120 /
  P3 OPEN LRAT 50.0531 105.322 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2015 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 135.152 174.581 6* RATE /
  I2 WATER OPEN 256.026 172.984 6* RATE /
  I3 WATER OPEN 216.206 176.043 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 24.8106 202.628 4* 120 /
  P2 OPEN LRAT 48.75 165.879 4* 120 /
  P3 OPEN LRAT 49.1768 106.934 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2015 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 135.816 174.625 6* RATE /
  I2 WATER OPEN 256.578 173.006 6* RATE /
  I3 WATER OPEN 217 176.071 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 24.5242 203.686 4* 120 /
  P2 OPEN LRAT 48.2648 166.989 4* 120 /
  P3 OPEN LRAT 48.3045 108.551 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2015 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 136.466 174.666 6* RATE /
  I2 WATER OPEN 257.103 173.029 6* RATE /
  I3 WATER OPEN 217.777 176.099 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 24.2485 204.708 4* 120 /
  P2 OPEN LRAT 47.8062 168.05 4* 120 /
  P3 OPEN LRAT 47.4872 110.082 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2015 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 137.122 174.708 6* RATE /
  I2 WATER OPEN 257.68 173.051 6* RATE /
  I3 WATER OPEN 218.58 176.129 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 23.9649 205.761 4* 120 /
  P2 OPEN LRAT 47.3383 169.142 4* 120 /
  P3 OPEN LRAT 46.6907 111.648 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2015 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 137.78 174.75 6* RATE /
  I2 WATER OPEN 258.258 173.077 6* RATE /
  I3 WATER OPEN 219.388 176.159 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 23.6832 206.811 4* 120 /
  P2 OPEN LRAT 46.8736 170.226 4* 120 /
  P3 OPEN LRAT 45.9087 113.202 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2015 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 138.422 174.792 6* RATE /
  I2 WATER OPEN 258.825 173.102 6* RATE /
  I3 WATER OPEN 220.179 176.19 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 23.4196 207.837 4* 120 /
  P2 OPEN LRAT 46.4269 171.27 4* 120 /
  P3 OPEN LRAT 45.1652 114.691 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2015 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 139.071 174.834 6* RATE /
  I2 WATER OPEN 259.443 173.128 6* RATE /
  I3 WATER OPEN 220.998 176.221 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 23.1556 208.903 4* 120 /
  P2 OPEN LRAT 45.9669 172.343 4* 120 /
  P3 OPEN LRAT 44.424 116.221 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2015 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 139.709 174.877 6* RATE /
  I2 WATER OPEN 260.041 173.157 6* RATE /
  I3 WATER OPEN 221.805 176.254 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 22.9029 209.936 4* 120 /
  P2 OPEN LRAT 45.5242 173.376 4* 120 /
  P3 OPEN LRAT 43.7224 117.697 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2015 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 140.344 174.92 6* RATE /
  I2 WATER OPEN 260.665 173.185 6* RATE /
  I3 WATER OPEN 222.618 176.288 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 22.6449 210.992 4* 120 /
  P2 OPEN LRAT 45.0697 174.43 4* 120 /
  P3 OPEN LRAT 43.002 119.208 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JAN 2016 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 140.976 174.961 6* RATE /
  I2 WATER OPEN 261.284 173.214 6* RATE /
  I3 WATER OPEN 223.43 176.321 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 22.3898 212.038 4* 120 /
  P2 OPEN LRAT 44.6218 175.474 4* 120 /
  P3 OPEN LRAT 42.2887 120.704 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 FEB 2016 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 141.578 175.003 6* RATE /
  I2 WATER OPEN 261.862 173.244 6* RATE /
  I3 WATER OPEN 224.201 176.355 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 22.1529 213.016 4* 120 /
  P2 OPEN LRAT 44.2085 176.442 4* 120 /
  P3 OPEN LRAT 41.6398 122.092 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAR 2016 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 142.187 175.045 6* RATE /
  I2 WATER OPEN 262.504 173.272 6* RATE /
  I3 WATER OPEN 225.005 176.388 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 21.904 214.062 4* 120 /
  P2 OPEN LRAT 43.7701 177.464 4* 120 /
  P3 OPEN LRAT 40.9657 123.56 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 APR 2016 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 142.793 175.084 6* RATE /
  I2 WATER OPEN 263.121 173.303 6* RATE /
  I3 WATER OPEN 225.798 176.421 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 21.6664 215.077 4* 120 /
  P2 OPEN LRAT 43.3518 178.446 4* 120 /
  P3 OPEN LRAT 40.3271 124.964 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 MAY 2016 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 143.401 175.125 6* RATE /
  I2 WATER OPEN 263.769 173.333 6* RATE /
  I3 WATER OPEN 226.605 176.456 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 21.4226 216.118 4* 120 /
  P2 OPEN LRAT 42.9254 179.453 4* 120 /
  P3 OPEN LRAT 39.6882 126.395 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUN 2016 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 144.001 175.165 6* RATE /
  I2 WATER OPEN 264.398 173.365 6* RATE /
  I3 WATER OPEN 227.398 176.491 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 21.192 217.127 4* 120 /
  P2 OPEN LRAT 42.5173 180.424 4* 120 /
  P3 OPEN LRAT 39.0805 127.772 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 JUL 2016 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 144.607 175.206 6* RATE /
  I2 WATER OPEN 265.064 173.397 6* RATE /
  I3 WATER OPEN 228.209 176.527 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 20.9599 218.174 4* 120 /
  P2 OPEN LRAT 42.0972 181.423 4* 120 /
  P3 OPEN LRAT 38.464 129.182 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 AUG 2016 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 145.228 175.245 6* RATE /
  I2 WATER OPEN 265.747 173.43 6* RATE /
  I3 WATER OPEN 229.04 176.563 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 20.7272 219.227 4* 120 /
  P2 OPEN LRAT 41.693 182.43 4* 120 /
  P3 OPEN LRAT 37.8648 130.586 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 SEP 2016 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 145.842 175.287 6* RATE /
  I2 WATER OPEN 266.422 173.464 6* RATE /
  I3 WATER OPEN 229.862 176.602 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 20.5061 220.254 4* 120 /
  P2 OPEN LRAT 41.3024 183.416 4* 120 /
  P3 OPEN LRAT 37.2977 131.949 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 OCT 2016 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 146.47 175.329 6* RATE /
  I2 WATER OPEN 267.139 173.499 6* RATE /
  I3 WATER OPEN 230.708 176.641 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 20.2827 221.323 4* 120 /
  P2 OPEN LRAT 40.9002 184.445 4* 120 /
  P3 OPEN LRAT 36.7158 133.351 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 NOV 2016 /
  /

WCONINJH                               -- Generated : Petrel
  I1 WATER OPEN 147.095 175.371 6* RATE /
  I2 WATER OPEN 267.844 173.535 6* RATE /
  I3 WATER OPEN 231.549 176.681 6* RATE /
  /

WCONHIST                               -- Generated : Petrel
  P1 OPEN LRAT 20.0654 222.363 4* 120 /
  P2 OPEN LRAT 40.5155 185.449 4* 120 /
  P3 OPEN LRAT 36.17 134.707 4* 120 /
  /

DATES                                  -- Generated : Petrel
  1 DEC 2016 /
  /

