-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2018.1 Schlumberger
-- User name   : eremyanga
-- Date        : Monday, November 30 2020 13:23:17
-- Project     : prepare_v4.pet
-- Generated ]

JFUNCR                                 -- Generated : Petrel
  WATER             25              0 0.5 0.5 /

INIT                                   -- Generated : Petrel

GRIDFILE                               -- Generated : Petrel
  0 0 /

GRIDUNIT                               -- Generated : Petrel
  METRES /

MAPUNITS                               -- Generated : Petrel
  METRES /

PINCH                                  -- Generated : Petrel
  4* ALL /

FAULTS                                 -- Generated : Petrel
-- FAULTS keyword exported here to support THPRESFT and MULTFLT keyword data. 
-- Matrix Faults

-- NAME          IX1  IX2     IY1  IY2     IZ1  IZ2    FACE
'FAULT1' 10 10 18 18 1 15 'X' / 
'FAULT1' 10 10 17 17 1 15 'X' / 
'FAULT1' 10 10 16 16 1 15 'X' / 
'FAULT1' 10 10 15 15 1 15 'X' / 
'FAULT1' 10 10 14 14 1 15 'X' / 
'FAULT1' 10 10 13 13 1 15 'X' / 
'FAULT1' 10 10 12 12 1 15 'X' / 
'FAULT1' 10 10 11 11 1 15 'X' / 
'FAULT1' 10 10 10 10 1 15 'X' / 
'FAULT1' 10 10 9 9 1 15 'X' / 
'FAULT1' 10 10 8 8 1 15 'X' / 
'FAULT1' 10 10 7 7 1 15 'X' / 
'FAULT1' 10 10 6 6 1 15 'X' / 
'FAULT1' 10 10 5 5 1 15 'X' / 
'FAULT1' 10 10 4 4 1 15 'X' / 
'FAULT1' 10 10 3 3 1 15 'X' / 
'FAULT1' 10 10 2 2 1 15 'X' / 
'FAULT1' 10 10 1 1 1 15 'X' / 

-- Mapping of unique fault names to full fault names (matrix):
-- FAULT1 ==> Fault 1
 
/

